# Generated by Django 4.2.5 on 2023-09-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todos",
            name="description",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="todos",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("pending", "Pending")],
                max_length=20,
            ),
        ),
    ]
